"""add review

Revision ID: 29966b181300
Revises: 0f42fb6d226d
Create Date: 2025-04-06 11:56:53.324527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29966b181300'
down_revision = '0f42fb6d226d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
