"""add review model with foreign keys (batch mode)

Revision ID: 821575d361d5
Revises: 29966b181300
Create Date: 2025-04-06 12:22:43.942376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821575d361d5'
down_revision = '29966b181300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_reviews_customer_id_customers'), 'customers', ['customer_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_reviews_item_id_items'), 'items', ['item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_item_id_items'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_reviews_customer_id_customers'), type_='foreignkey')

    # ### end Alembic commands ###
